/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_demo_yzy_DiffUtil */

#ifndef _Included_com_demo_yzy_DiffUtil
#define _Included_com_demo_yzy_DiffUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_yzy_DiffUtil
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_demo_yzy_DiffUtil_diff
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
