/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_yzy_diffandpatchproject_DiffAndPatchUtil */

#ifndef _Included_com_yzy_diffandpatchproject_DiffAndPatchUtil
#define _Included_com_yzy_diffandpatchproject_DiffAndPatchUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yzy_diffandpatchproject_DiffAndPatchUtil
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yzy_diffandpatchproject_DiffAndPatchUtil_diff
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_yzy_diffandpatchproject_DiffAndPatchUtil
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yzy_diffandpatchproject_DiffAndPatchUtil_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
